services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ibexa\Contracts\CoreSearch\Values\Query\CriterionMapper:
        arguments:
            $mappers: !tagged_iterator ibexa.core_search.criterion_mapper
